# Generated by Django 3.2.18 on 2023-05-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('username', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('alternative_contact', models.CharField(blank=True, max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('personal_email', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Technology',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducationDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hrmsApp.employee')),
                ('ssc_school_name', models.CharField(max_length=50)),
                ('ssc_passout_year', models.CharField(max_length=5, null=True)),
                ('ssc_percentage', models.FloatField()),
                ('hsc_college_name', models.CharField(max_length=50)),
                ('hsc_passout_year', models.CharField(max_length=5)),
                ('hsc_stream', models.CharField(max_length=50)),
                ('hsc_percentage', models.FloatField()),
                ('ug_college_name', models.CharField(max_length=50)),
                ('ug_passout_year', models.CharField(max_length=5)),
                ('ug_stream', models.CharField(max_length=15)),
                ('ug_specialization', models.CharField(max_length=50)),
                ('ug_percentage', models.FloatField()),
                ('pg_college_name', models.CharField(max_length=50)),
                ('pg_passout_year', models.CharField(max_length=5)),
                ('pg_stream', models.CharField(max_length=15)),
                ('pg_specialization', models.CharField(max_length=50)),
                ('pg_percentage', models.FloatField()),
                ('education_gap', models.CharField(blank=True, max_length=10, null=True)),
                ('gap_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'employees_education_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOfficialDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hrmsApp.employee')),
                ('official_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('bank_acount_number', models.CharField(max_length=30)),
                ('aadhaar', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=10)),
                ('universal_acount_number', models.CharField(max_length=50)),
                ('esic_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employees_official_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeePackageDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hrmsApp.employee')),
                ('package', models.FloatField()),
                ('bonus', models.FloatField()),
                ('in_hand_salary', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('basic_salary', models.FloatField()),
                ('erf', models.FloatField()),
                ('hra', models.FloatField()),
                ('travell_allowance', models.FloatField()),
                ('medical_allowance', models.FloatField()),
                ('other_allowance', models.FloatField()),
                ('esic', models.FloatField()),
                ('pt', models.FloatField()),
            ],
            options={
                'db_table': 'employees_package_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hrmsApp.employee')),
                ('internship_start_date', models.DateField()),
                ('internship_end_date', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_leave', models.DateField()),
            ],
            options={
                'db_table': 'employees_work_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkExperience',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hrmsApp.employee')),
                ('company_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('internship_company', models.CharField(max_length=50)),
                ('internship_start_date', models.DateField()),
                ('internship_end_date', models.DateField()),
            ],
            options={
                'db_table': 'employees_work_experience',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf', models.FloatField()),
                ('professional_tax', models.FloatField()),
                ('other_charges', models.FloatField()),
                ('tds', models.FloatField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.employee')),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid_leaves', models.IntegerField(default=1)),
                ('used_paid_leaves', models.IntegerField(default=0)),
                ('paid_leave_balance', models.IntegerField(default=1)),
                ('comp_off_leave', models.IntegerField(default=0)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.employee')),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('logindatetime', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.employee')),
            ],
            options={
                'db_table': 'employee_login',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.IntegerField()),
                ('leave_type', models.CharField(max_length=30)),
                ('leave_from', models.DateField()),
                ('leave_till', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('leave_reason', models.TextField()),
                ('is_aproved', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.employee')),
            ],
            options={
                'db_table': 'employees_leave',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in_time', models.TimeField(auto_now=True)),
                ('out_time', models.TimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.employee')),
            ],
            options={
                'db_table': 'employees_attendance',
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.employee')),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('logindatetime', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.admins')),
            ],
            options={
                'db_table': 'admin_login',
            },
        ),
    ]
