# Generated by Django 4.2.1 on 2023-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('alternative_contact', models.CharField(blank=True, max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
            options={
                'verbose_name': 'employee',
            },
        ),
    ]
