# Generated by Django 4.2.1 on 2023-06-16 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0003_auto_20230601_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('status', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.employee')),
            ],
            options={
                'db_table': 'otpauthentication',
            },
        ),
    ]
