# Generated by Django 4.2.1 on 2023-05-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0003_alter_employee_emp_id_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1123, max_length=100),
            preserve_default=False,
        ),
    ]
