# Generated by Django 4.2.1 on 2023-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0004_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhaar',
            field=models.CharField(default=1234567, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pan',
            field=models.EmailField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.EmailField(db_index=True, max_length=30, unique=True),
        ),
    ]
