# Generated by Django 4.2.1 on 2023-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0005_employee_aadhaar_employee_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.EmailField(db_index=True, max_length=50, unique=True),
        ),
    ]
