# Generated by Django 4.2.1 on 2023-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0006_alter_employee_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pan',
            field=models.CharField(max_length=10),
        ),
    ]
