# Generated by Django 4.2.1 on 2023-06-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0006_employeepslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='encashment_leave',
            field=models.IntegerField(default=0),
        ),
    ]
