# Generated by Django 4.2.1 on 2023-05-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0007_alter_employee_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsApp.employee')),
            ],
            options={
                'verbose_name': 'employee_education_details',
            },
        ),
    ]
