# Generated by Django 4.2.1 on 2023-06-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0007_leave_encashment_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='total_casual_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
