# Generated by Django 4.2.1 on 2023-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0008_employeeeducationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeeducationdetails',
            name='addr',
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='ssc_passout_year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='ssc_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='ssc_school_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
