# Generated by Django 4.2.1 on 2023-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0008_leave_total_casual_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
