# Generated by Django 4.2.1 on 2023-05-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0009_remove_employeeeducationdetails_addr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='hsc_college_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='hsc_passout_year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='hsc_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='hsc_stream',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='pg_college_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='pg_passout_year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='pg_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='pg_specialization',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='pg_stream',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='ug_college_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='ug_passout_year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='ug_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='ug_specialization',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='ug_stream',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
