# Generated by Django 4.2.1 on 2023-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0010_employeeeducationdetails_hsc_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='education_gap',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='gap_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
