# Generated by Django 4.2.1 on 2023-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0012_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepslip',
            name='paid_days',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='employeepslip',
            name='total_present_days',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='employeepslip',
            name='total_working_days',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
