# Generated by Django 3.2.18 on 2023-06-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0013_employeepslip_paid_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
