# Generated by Django 3.2.18 on 2023-06-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0014_delete_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='comp_off_leave',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='encashment_leave',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='paid_leave_balance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='total_casual_leaves',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='total_paid_leaves',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='used_paid_leaves',
            field=models.IntegerField(blank=True),
        ),
    ]
